# Generated by Django 4.0.3 on 2023-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_uname_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
    ]
