# Generated by Django 4.0.3 on 2023-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
