# Generated by Django 4.0.3 on 2023-04-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_complete_percentage_task_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_date',
            field=models.DateField(null=True),
        ),
    ]
