# Generated by Django 4.0.3 on 2023-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurring_task_date',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='remind_me_date',
            field=models.JSONField(),
        ),
    ]
