# Generated by Django 4.0.3 on 2023-04-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_task_recurring_task_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurring_task_date',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='task',
            name='remind_me_date',
            field=models.JSONField(default=[]),
        ),
    ]
