# Generated by Django 4.0.3 on 2023-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
