# Generated by Django 4.0.3 on 2023-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_task_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
