# Generated by Django 4.0.3 on 2023-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media',
            field=models.ImageField(default='', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
