# Generated by Django 4.0.3 on 2023-06-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
