# Generated by Django 4.0.3 on 2023-06-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_task_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taking_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
