# Generated by Django 4.0.3 on 2023-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_task_taking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creation_date',
        ),
    ]
