# Generated by Django 4.0.3 on 2023-06-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_task_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taking_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
