# Generated by Django 4.0.3 on 2023-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_task_taking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='support',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
