# Generated by Django 4.0.3 on 2023-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_feedback_user_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
