# Generated by Django 4.0.3 on 2023-07-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taking_date',
        ),
        migrations.AddField(
            model_name='task',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
    ]
