# Generated by Django 4.0.3 on 2023-07-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_task_taking_date_task_reminded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='remind_me',
        ),
        migrations.RemoveField(
            model_name='task',
            name='remind_me_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='user',
            name='support',
        ),
    ]
